[theme]
primaryColor = "#635BFF"
backgroundColor = "#F6F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0E0F13"
font = "sans serif"

[server]
maxUploadSize = 25
headless = true
fileWatcherType = "none"
